# Pake Nginx biar enteng kayak MacBook M4 lo
FROM nginx:alpine

# Copy file HTML lo ke folder default Nginx
# Kalau index.html ada di dalem folder 'public'
COPY public/index.html /usr/share/nginx/html/index.html

EXPOSE 80